/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
 */
package projecteuler;
/**
 *
 * @author AVINASH
 */
public class EvenFibonacciNumbers {
    public static void main(String[] args){
        int curr=2,prev=1;
        int sum=2;
        int fib=0;
        while(fib<4000000){
            fib=curr+prev;
            if(fib%2==0){
                sum+=fib;
            }
            prev=curr;
            curr=fib;
        }
        System.out.println("Sum of even fibo: "+sum); //Answer: 4613732
    }
}